[package]
name = "pdf_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
kamadak-exif = "0.6.1"
printpdf = { version = "0.8.2", features = ["png", "jpeg"] }
taffy = "0.9.2"
